language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    
branches:
  only:
  - develop

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install -e .
- pip install coveralls

before_script:
- flake8 edc_action_item
- psql -c 'create database edc encoding=UTF8;' -U postgres

script:
- coverage run --source=edc_action_item manage.py test

after_success:
- coveralls
