# Generated by Django 2.0 on 2017-12-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='instructions',
            field=models.TextField(blank=True, editable=False, help_text='populated by action class', null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='instructions',
            field=models.TextField(blank=True, editable=False, help_text='populated by action class', null=True),
        ),
    ]
