# Generated by Django 2.0rc1 on 2017-11-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
